server:
  port: 7001
  use-forward-headers: true
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500
    min-spare-threads: 300


logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"

